name: Auto Update USA Config

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests urllib3

      - name: Run USA Tester
        run: python test_from_usa.py

      - name: Auto Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update USA config"
          file_pattern: 'usa_config.txt'
